<?php

return $admin_form_data = array(
    'general' => array(
        'ota_url' => '',
        'status' => true,
        'wid_bg_color' => 'rgba(0, 0, 0, 0.5)',
        'wid_font_color' => '#fafafa',
        'btn_bg_color' => 'rgba(255, 131, 0, 0.94)',
        'btn_font_color' => '#fafafa',
        'widget_width' => '100',
        'widget_align' => 'center',
        'widget_border' => '0',
        'widget_border_color' => '#212121',
        'widget_border_radius' => '0',
        'widget_btn_border_radius' => '4',
        'widget_inpt_border_radius' => '4',
        'widget_inpt_bg_color' => 'rgba(0, 0, 0, 0.5)',
        'widget_inpt_fnt_color' => '#212121',
        'widget_clndr_bg_color' => 'rgba(0, 0, 0, 0.5)',
        'widget_clndr_fnt_color' => '#fafafa',
        'custom_styles' => ''
        ),

    'hotel' => array(
        'status' => true,
        'ht_location_title' => 'Destination',
        'ht_location_pholder' => 'Where do you wanna go?',
        'ht_checkin_title' => 'Check In',
        'ht_checkout_title' => 'Check Out',
        'ht_nights_title' => 'Nights',
        'ht_nights_count' => 10,
        ),
    'transfer' => array(
        'status' => true,
        'pickup_loc_title' => 'Pick-up Location',
        'pickup_loc_pholder' => 'Pick-up Location',
        'drop_loc_title' => 'Drop-off Location',
        'drop_loc_pholder' => 'Drop-off Location',
        'pickup_dat_title' => 'Pick-up date',
        'pickup_time_title' => 'Pick-up Time',
        'return_dat_title' => 'Return date',
        'return_time_title' => 'Return Time',
        ),
    'activities' => array(
        'status' => true,
        'destination_label' => 'Destination',
        'destination_phold' => 'Type and select your destination',
        'adult_count' => 4,
        'child_count' => 4,
        'child_age' => 15,
        'from_date_label' => 'From',
        'to_date_label' => 'To',
        ),
    'car_rental' => array(
        'status' => true,
        'ret_same_loc_title' => 'Return Car To The Same Location',
        'ret_pickup_type_title' => 'Pick-up Type',
        'ret_pickup_title' => 'Pick-up',
        'ret_pickup_pholder' => 'Pick-up Location',
        'ret_pickup_date_title' => 'From',
        'ret_pickup_time_title' => 'Pick-up Time',
        'ret_return_type_title' => 'Return Type',
        'ret_return_title' => 'Return',
        'ret_return_pholder' => 'Return Location',
        'ret_return_date_title' => 'To',
        'ret_return_time_title' => 'Return Time',
        'ret_driver_age_title' => 'Drivers Age',
        ),
    'flights' => array(
        'status' => true,
        'fl_from_title' => 'From',
        'fl_from_pholder' => 'Enter Origin City',
        'fl_to_title' => 'To',
        'fl_to_pholder' => 'Enter Destination city',
        'fl_depature_title' => 'Departure',
        'fl_arrival_title' => 'Arrival',
        'fl_passangers_title' => 'Passengers',
        'fl_ticket_type_title' => 'Ticket Type',
        'fl_trip_type_title' => 'Trip Type',
        )
    );